export const COIN_ICONS = {
  AAVE: "/coin-icons/AAVE-icon.png",
  ADA: "/coin-icons/ADA-icon.png",
  APT: "/coin-icons/APT-icon.png",
  AVAX: "/coin-icons/AVAX-icon.png",
  AXS: "/coin-icons/AXS-icon.png",
  BCH: "/coin-icons/BCH-icon.png",
  DAI: "/coin-icons/DAI-icon.png",
  DOGE: "/coin-icons/DOGE-icon.png",
  DOT: "/coin-icons/DOT-icon.png",
  DUSK: "/coin-icons/DUSK-icon.png",
  FIL: "/coin-icons/FIL-icon.png",
  FOGO: "/coin-icons/FOGO-icon.png",
  HBAR: "/coin-icons/HBAR-icon.png",
  ICP: "/coin-icons/ICP-icon.png",
  LINK: "/coin-icons/LINK-icon.png",
  MET: "/coin-icons/MET-icon.png",
  PEPE: "/coin-icons/PEPE-icon.png",
  SHIB: "/coin-icons/SHIB-icon.png",
  SKY: "/coin-icons/SKY-icon.png",
  SOL: "/coin-icons/SOL-icon.png",
  SUI: "/coin-icons/SUI-icon.png",
  TON: "/coin-icons/TON-icon.png",
  TRUMP: "/coin-icons/TRUMP-icon.png",
  TRX: "/coin-icons/TRX-icon.png",
  U: "/coin-icons/U-icon.png",
  UNI: "/coin-icons/UNI-icon.png",
  USD1: "/coin-icons/USD1-icon.png",
  USDC: "/coin-icons/USDC-icon.png",
  USDE: "/coin-icons/USDE-icon.png",
  USDT: "/coin-icons/USDT-icon.png",
  WBETH: "/coin-icons/WBETH-icon.png",
  WBTC: "/coin-icons/WBTC-icon.png",
  WLD: "/coin-icons/WLD-icon.png",
  WLFI: "/coin-icons/WLFI-icon.png",
  XLM: "/coin-icons/XLM-icon.png",
  ZEC: "/coin-icons/ZEC-icon.png",
  ZKP: "/coin-icons/ZKP-icon.png",
  ASTR: "/coin-icons/aster-icon.png",
  BTC: "/coin-icons/bitcoin-icon.png",
  BNB: "/coin-icons/bnb-icon.png",
  ETH: "/coin-icons/ethereum-icon.png",
  XRP: "/coin-icons/xrp-icon.png",
};

export const getCoinIcon = (symbol) => {
  return COIN_ICONS[symbol.toUpperCase()] || null;
};
